/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.EscritorController;
import dao.ExceptionDAO;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.Escritor;

/**
 *
 * @author debor
 */
public class TelaConsultarAutor extends javax.swing.JFrame {
 
    private TelaAutor  telaAutor;
    /**
     * Creates new form TelaConsultarAutor
     */
    
     public TelaConsultarAutor(TelaAutor telaAutor){
         this.telaAutor = telaAutor;
         initComponents();
     }
    public TelaConsultarAutor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelConsultarAutor = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldCampoNomeAutor = new javax.swing.JTextField();
        jButtonConsultarSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsultarAutor = new javax.swing.JTable();
        jLabelConsultarAutor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca leia um livro");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                FecharJanela(evt);
            }
        });

        jPanelConsultarAutor.setBackground(new java.awt.Color(102, 102, 102));

        jLabelNome.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNome.setText("Insira o nome do Autor:");

        jTextFieldCampoNomeAutor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldCampoNomeAutor.setText("Insira o nome...");
        jTextFieldCampoNomeAutor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonConsultarSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        jButtonConsultarSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonConsultarSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarSearch(evt);
            }
        });

        jTableConsultarAutor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTableConsultarAutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "código", "Nome", "Nacionalidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableConsultarAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultarAutorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableConsultarAutor);

        javax.swing.GroupLayout jPanelConsultarAutorLayout = new javax.swing.GroupLayout(jPanelConsultarAutor);
        jPanelConsultarAutor.setLayout(jPanelConsultarAutorLayout);
        jPanelConsultarAutorLayout.setHorizontalGroup(
            jPanelConsultarAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultarAutorLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanelConsultarAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelConsultarAutorLayout.createSequentialGroup()
                        .addComponent(jLabelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCampoNomeAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConsultarSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanelConsultarAutorLayout.setVerticalGroup(
            jPanelConsultarAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultarAutorLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanelConsultarAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonConsultarSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelConsultarAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldCampoNomeAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLabelConsultarAutor.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabelConsultarAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/book.png"))); // NOI18N
        jLabelConsultarAutor.setText("Consultar Autor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelConsultarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabelConsultarAutor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabelConsultarAutor)
                .addGap(18, 18, 18)
                .addComponent(jPanelConsultarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultarSearch(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarSearch
        String nome = jTextFieldCampoNomeAutor.getText();
      DefaultTableModel tableModel = (DefaultTableModel) jTableConsultarAutor.getModel();
      tableModel.setRowCount(0);
      EscritorController escritorController = new EscritorController();
      try{
          ArrayList<Escritor> escritores = escritorController.listarAutores(nome);
          escritores.forEach((Escritor escritor) -> {
              tableModel.addRow(new Object[] { escritor.getCodAutores(),
                                               escritor.getNome(),
                                               escritor.getNacionalidade()});
                                               
              });
         jTableConsultarAutor.setModel(tableModel);
      } catch (ExceptionDAO ex) {
            Logger.getLogger(TelaAutor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ConsultarSearch

    private void FecharJanela(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_FecharJanela
        this.dispose();
        this.telaAutor.setVisible(true);
    }//GEN-LAST:event_FecharJanela

    private void jTableConsultarAutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultarAutorMouseClicked
        if(evt.getClickCount()==2){
           Integer codAutor = (Integer) jTableConsultarAutor.getModel().getValueAt(jTableConsultarAutor.getSelectedRow(), 0);
           String nome = (String) jTableConsultarAutor.getModel().getValueAt(jTableConsultarAutor.getSelectedRow(), 1);
           String nacionalidade = (String) jTableConsultarAutor.getModel().getValueAt(jTableConsultarAutor.getSelectedRow(), 2);
          
           
           this.telaAutor.buscarAtor(codAutor, nome, nacionalidade);
           
           this.telaAutor.setVisible(true);
           this.dispose();
       }
    }//GEN-LAST:event_jTableConsultarAutorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultarAutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultarSearch;
    private javax.swing.JLabel jLabelConsultarAutor;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JPanel jPanelConsultarAutor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsultarAutor;
    private javax.swing.JTextField jTextFieldCampoNomeAutor;
    // End of variables declaration//GEN-END:variables
}
