/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClienteController;
import dao.ExceptionDAO;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.Cliente;

/**
 *
 * @author debor
 */
public class TelaConsultarCliente extends javax.swing.JFrame {
private TelaCliente telaCliente;
    /**
     * Creates new form TelaConsultarCliente
     */
public TelaConsultarCliente(TelaCliente telaCliente){
    this.telaCliente = telaCliente;
    initComponents();
}
    public TelaConsultarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelConsultarCliente = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldCampoNome = new javax.swing.JTextField();
        jButtonConsultarSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsultarCliente = new javax.swing.JTable();
        jLabelConsultarCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca leia um livro");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                FecharJanela(evt);
            }
        });

        jPanelConsultarCliente.setBackground(new java.awt.Color(102, 102, 102));
        jPanelConsultarCliente.setToolTipText("");

        jLabelNome.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNome.setText("NOME:");

        jTextFieldCampoNome.setToolTipText("Insira o nome...");
        jTextFieldCampoNome.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldCampoNome.setPreferredSize(new java.awt.Dimension(50, 10));

        jButtonConsultarSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        jButtonConsultarSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonConsultarSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarClientes(evt);
            }
        });

        jTableConsultarCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTableConsultarCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "código", "Nome", "Cpf", "Email", "Endereço", "Nascimento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableConsultarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultarClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableConsultarCliente);

        javax.swing.GroupLayout jPanelConsultarClienteLayout = new javax.swing.GroupLayout(jPanelConsultarCliente);
        jPanelConsultarCliente.setLayout(jPanelConsultarClienteLayout);
        jPanelConsultarClienteLayout.setHorizontalGroup(
            jPanelConsultarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultarClienteLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanelConsultarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelConsultarClienteLayout.createSequentialGroup()
                        .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonConsultarSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanelConsultarClienteLayout.setVerticalGroup(
            jPanelConsultarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultarClienteLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanelConsultarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonConsultarSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelConsultarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jLabelConsultarCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabelConsultarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/book.png"))); // NOI18N
        jLabelConsultarCliente.setText("Consultar Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabelConsultarCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelConsultarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabelConsultarCliente)
                .addGap(18, 18, 18)
                .addComponent(jPanelConsultarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultarClientes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarClientes
        String nome = jTextFieldCampoNome.getText();
      DefaultTableModel tableModel = (DefaultTableModel) jTableConsultarCliente.getModel();
      tableModel.setRowCount(0);
      ClienteController clienteController = new ClienteController();
      try{
          ArrayList<Cliente> clientes = clienteController.listarClientes(nome);
          clientes.forEach((Cliente cliente) -> { 
          tableModel.addRow(new Object[] {     cliente.getCodCliente(),
                                               cliente.getNome(),
                                               cliente.getCpf(),
                                               cliente.getEmail(),
                                               cliente.getEndereco(),
                                               cliente.getNascimento()});
              });
         jTableConsultarCliente.setModel(tableModel);
      } catch (ExceptionDAO ex) {
            Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ConsultarClientes

    private void FecharJanela(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_FecharJanela
        this.dispose();
        this.telaCliente.setVisible(true);
    }//GEN-LAST:event_FecharJanela

    private void jTableConsultarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultarClienteMouseClicked
        if(evt.getClickCount()==2){
           Integer codCliente  = (Integer) jTableConsultarCliente.getModel().getValueAt(jTableConsultarCliente.getSelectedRow(), 0);
           String nome = (String) jTableConsultarCliente.getModel().getValueAt(jTableConsultarCliente.getSelectedRow(), 1);
           String cpf = (String) jTableConsultarCliente.getModel().getValueAt(jTableConsultarCliente.getSelectedRow(), 2);
           String email = (String) jTableConsultarCliente.getModel().getValueAt(jTableConsultarCliente.getSelectedRow(), 3);
           String endereco = (String) jTableConsultarCliente.getModel().getValueAt(jTableConsultarCliente.getSelectedRow(), 4);
           Date nascimento = (Date) jTableConsultarCliente.getModel().getValueAt(jTableConsultarCliente.getSelectedRow(), 5);
           this.telaCliente.buscarCliente(WIDTH, nome, cpf, email, endereco, nascimento);
           
           this.telaCliente.setVisible(true);
           this.dispose();
       }
    }//GEN-LAST:event_jTableConsultarClienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultarSearch;
    private javax.swing.JLabel jLabelConsultarCliente;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JPanel jPanelConsultarCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsultarCliente;
    private javax.swing.JTextField jTextFieldCampoNome;
    // End of variables declaration//GEN-END:variables

   
}
