/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.LivroController;
import dao.ExceptionDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author debor
 */
public class TelaCadastroLivros extends javax.swing.JFrame {
    private TelaPrincipal telaPrincipal;
    private Integer codLivro = 0;
    /**
     * Creates new form TelaCadastroLivros
     * @param telaPrincipal
     */
    public TelaCadastroLivros(TelaPrincipal telaPrincipal) {
        initComponents();
        this.telaPrincipal = telaPrincipal;
    }
    public TelaCadastroLivros() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void buscarLivro(Integer codLivro, String titulo, String genero, String sinopse, Integer numPaginas){
        this.codLivro = codLivro;
        this.jTextFieldCampoTitulo.setText(titulo);
        for(int contador=0;contador<jComboBoxCampoGenero.getItemCount();contador++){
            if(jComboBoxCampoGenero.getItemAt(contador).equals(genero))
                    jComboBoxCampoGenero.setSelectedIndex(contador);
        }
            this.jTextPaneCampoResumo.setText(sinopse);
            for(int contador=0;contador<jComboBoxCampoPaginas.getItemCount();contador++){
            if(jComboBoxCampoPaginas.getItemAt(contador).equals(numPaginas))
                    jComboBoxCampoPaginas.setSelectedIndex(contador);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCadastroLivro = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelGenero = new javax.swing.JLabel();
        jLabelResumo = new javax.swing.JLabel();
        jLabelPaginas = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();
        jTextFieldCampoTitulo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneCampoResumo = new javax.swing.JTextArea();
        jComboBoxCampoPaginas = new javax.swing.JComboBox<>();
        jComboBoxCampoGenero = new javax.swing.JComboBox<>();
        jButtonApagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca Leia um Livro");
        setBackground(new java.awt.Color(153, 153, 153));
        setResizable(false);

        jLabelCadastroLivro.setBackground(new java.awt.Color(128, 128, 128));
        jLabelCadastroLivro.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabelCadastroLivro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCadastroLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/book.png"))); // NOI18N
        jLabelCadastroLivro.setText("Cadastro de Livros");

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTitulo.setText("TÍTULO:");

        jLabelGenero.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelGenero.setText("GÊNERO:");

        jLabelResumo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelResumo.setText("RESUMO:");

        jLabelPaginas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelPaginas.setText("PÁGINAS:");

        jButtonSalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonLimpar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonConsultar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonConsultar.setText("Consultar");
        jButtonConsultar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrir_TelaConsultarLivro(evt);
            }
        });

        jTextFieldCampoTitulo.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldCampoTitulo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldCampoTitulo.setText("Insira o nome...");
        jTextFieldCampoTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextPaneCampoResumo.setBackground(new java.awt.Color(153, 153, 153));
        jTextPaneCampoResumo.setColumns(20);
        jTextPaneCampoResumo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextPaneCampoResumo.setRows(5);
        jTextPaneCampoResumo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(jTextPaneCampoResumo);

        jComboBoxCampoPaginas.setBackground(new java.awt.Color(153, 153, 153));
        jComboBoxCampoPaginas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBoxCampoPaginas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "15", "20", "30", "40", "50", "60", "70", "80", "90", "100", "150", "200", "250", "300", "350", "400", "450", "500", "600", "700", "800", "900", "1000" }));
        jComboBoxCampoPaginas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBoxCampoPaginas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCampoPaginasActionPerformed(evt);
            }
        });

        jComboBoxCampoGenero.setBackground(new java.awt.Color(153, 153, 153));
        jComboBoxCampoGenero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBoxCampoGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ação", "Animação", "Aventura", "Cinema de arte", "Chanchada", "Comédia", "Comédia romântica", "Comédia dramática", "Comédia de ação", "Dança", "Documentário", "Docuficção", "Drama", "Espionagem", "Faroeste", "Fantasia científica", "Ficção científica", "Filmes de guerra", "Filme policial", "Musical", "Romance", "Seriado", "Suspense", "Terror" }));
        jComboBoxCampoGenero.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonApagar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonApagar.setText("Apagar");
        jButtonApagar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(241, 241, 241)
                            .addComponent(jLabelCadastroLivro))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelGenero)
                                .addComponent(jLabelTitulo))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldCampoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxCampoGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelResumo)
                                .addComponent(jLabelPaginas))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxCampoPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jButtonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jButtonApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCadastroLivro)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo)
                    .addComponent(jTextFieldCampoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelGenero)
                    .addComponent(jComboBoxCampoGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelResumo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxCampoPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPaginas))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonLimpar)
                            .addComponent(jButtonCancelar)
                            .addComponent(jButtonSalvar)
                            .addComponent(jButtonConsultar)
                            .addComponent(jButtonApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
        telaPrincipal.setVisible(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jComboBoxCampoPaginasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCampoPaginasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCampoPaginasActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jTextFieldCampoTitulo.setText("");
        jComboBoxCampoGenero.setSelectedIndex(0);
        jTextPaneCampoResumo.setText("");
        jComboBoxCampoPaginas.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void abrir_TelaConsultarLivro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrir_TelaConsultarLivro
        TelaConsultarLivro telaConsultarLivro = new TelaConsultarLivro(this);
        telaConsultarLivro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_abrir_TelaConsultarLivro

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        int numPaginas = Integer.parseInt(jComboBoxCampoPaginas.getItemAt(0).toString());
        String genero = jComboBoxCampoGenero.getSelectedItem().toString();
        boolean sucesso; 
    
    try{
       LivroController livroController = new LivroController();
       if(this.codLivro==0){
           sucesso = livroController.cadastraLivro(jTextFieldCampoTitulo.getText(),genero, jTextPaneCampoResumo.getText(), numPaginas);
       }else{
           sucesso = livroController.alterarLivro(this.codLivro, jTextFieldCampoTitulo.getText(),genero, jTextPaneCampoResumo.getText(), numPaginas);
       }
        if(sucesso ==true){
            JOptionPane.showMessageDialog(null, "O livro foi cadastrado!");
        this.jButtonLimparActionPerformed(evt); 
        }else{
            JOptionPane.showMessageDialog(null, "Os campos nao foram preenchidos corretamente!");
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "ERROR:" + e);
        }
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed
        boolean sucesso;
        LivroController livroController = new LivroController();
        try{
            sucesso = livroController.apagarLivro(this.codLivro);
            if(sucesso){
                JOptionPane.showMessageDialog(null, "Livro apagado!");
                this.jButtonLimparActionPerformed(evt);
            }else{
                JOptionPane.showMessageDialog(null, "Error ao apagar livro, por favor selecione novamente.");
            }
        } catch (ExceptionDAO ex) {
            Logger.getLogger(TelaCadastroLivros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonApagarActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroLivros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxCampoGenero;
    private javax.swing.JComboBox<String> jComboBoxCampoPaginas;
    private javax.swing.JLabel jLabelCadastroLivro;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelPaginas;
    private javax.swing.JLabel jLabelResumo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCampoTitulo;
    private javax.swing.JTextArea jTextPaneCampoResumo;
    // End of variables declaration//GEN-END:variables

}