/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClienteController;
import dao.ExceptionDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author debor
 */
public class TelaCliente extends javax.swing.JFrame {
    private TelaPrincipal telaPrincipal;
    private Integer codCliente = 0;
    /**
     * Creates new form TelaCliente
     */
    public TelaCliente() {
        initComponents();
    }
    //Construtor que faz a transicao da tela
public TelaCliente(TelaPrincipal telaPrincipal) {
        initComponents();
        this.telaPrincipal = telaPrincipal;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCadastroCliente = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldCampoNome = new javax.swing.JTextField();
        jLabelCpf = new javax.swing.JLabel();
        jLabelNascimento = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelEndereco = new javax.swing.JLabel();
        jTextFieldCampoNascimento = new javax.swing.JTextField();
        jTextFieldCampoCpf = new javax.swing.JTextField();
        jTextFieldCampoEmail = new javax.swing.JTextField();
        jTextFieldCampoEndereco = new javax.swing.JTextField();
        jButton1Salvar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();
        jButtonApagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca Leia um Livro");
        setResizable(false);

        jLabelCadastroCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabelCadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/book.png"))); // NOI18N
        jLabelCadastroCliente.setText("Cadastro de Clientes");

        jLabelNome.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelNome.setText("NOME:");

        jTextFieldCampoNome.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldCampoNome.setText("Insira o nome...");
        jTextFieldCampoNome.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelCpf.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelCpf.setText("CPF:");
        jLabelCpf.setToolTipText("");

        jLabelNascimento.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelNascimento.setText("NASCIMENTO:");

        jLabelEmail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelEmail.setText("E-MAIL:");

        jLabelEndereco.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelEndereco.setText("ENDEREÇO:");

        jTextFieldCampoNascimento.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldCampoNascimento.setText("data...");
        jTextFieldCampoNascimento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldCampoNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCampoNascimentoActionPerformed(evt);
            }
        });

        jTextFieldCampoCpf.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldCampoCpf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldCampoCpf.setText("xxx.xxx.xxx-xx");
        jTextFieldCampoCpf.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldCampoEmail.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldCampoEmail.setText("seuEmail@gmail.com");
        jTextFieldCampoEmail.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldCampoEndereco.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldCampoEndereco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldCampoEndereco.setText("Seu endereço...");
        jTextFieldCampoEndereco.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1Salvar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1Salvar.setText("Salvar");
        jButton1Salvar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SalvarActionPerformed(evt);
            }
        });

        jButtonLimpar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarCadastroCliente(evt);
            }
        });

        jButtonConsultar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonConsultar.setText("Consultar");
        jButtonConsultar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrir_ConsultarCliente(evt);
            }
        });

        jButtonApagar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonApagar.setText("Apagar");
        jButtonApagar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jLabelCadastroCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNascimento)
                            .addComponent(jLabelNome)
                            .addComponent(jLabelEmail)
                            .addComponent(jLabelEndereco)
                            .addComponent(jLabelCpf)
                            .addComponent(jButton1Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldCampoNome)
                                .addComponent(jTextFieldCampoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldCampoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldCampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldCampoEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(jButtonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jButtonApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCadastroCliente)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNascimento)
                    .addComponent(jTextFieldCampoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCpf)
                    .addComponent(jTextFieldCampoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldCampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEndereco)
                    .addComponent(jTextFieldCampoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
MaskFormatter mascaraCpf = null;
    private void jTextFieldCampoCpfActionPerfomed(java.awt.event.ActionEvent evt){
        try {
            // TODO add your handling code here:
            mascaraCpf = new MaskFormatter("###.###.###-##");
        } catch (ParseException ex) {
            Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    MaskFormatter mascaraData = null;
    private void jTextFieldCampoNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCampoNascimentoActionPerformed
         try {
            mascaraData = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextFieldCampoNascimentoActionPerformed

    private void abrir_ConsultarCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrir_ConsultarCliente
       TelaConsultarCliente telaConsultarCliente = new TelaConsultarCliente(this);
       this.setVisible(false);
       telaConsultarCliente.setVisible(true);
    }//GEN-LAST:event_abrir_ConsultarCliente

    private void CancelarCadastroCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarCadastroCliente
        this.dispose();
        telaPrincipal.setVisible(true);
    }//GEN-LAST:event_CancelarCadastroCliente

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jTextFieldCampoNome.setText("");
        jTextFieldCampoCpf.setText("");
        jTextFieldCampoEmail.setText("");
        jTextFieldCampoEndereco.setText("");
        jTextFieldCampoNascimento.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButton1SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SalvarActionPerformed
       boolean sucesso;
    
    try{
        
        ClienteController clienteController = new ClienteController();
        if(codCliente == 0){
        sucesso = clienteController.cadastrarCliente(jTextFieldCampoNome.getText(), jTextFieldCampoCpf.getText(), jTextFieldCampoEmail.getText(),
                jTextFieldCampoEndereco.getText(), jTextFieldCampoNascimento.getText());
        }else{
            sucesso = clienteController.alterarCliente(this.codCliente, jTextFieldCampoNome.getText(), jTextFieldCampoCpf.getText(), jTextFieldCampoEmail.getText(),
                jTextFieldCampoEndereco.getText(), jTextFieldCampoNascimento.getText());
        }
        if(sucesso == true){
            JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso!");
            this.jButtonLimparActionPerformed(evt);
        }else{
            JOptionPane.showMessageDialog(null, "Verifique os campos que nao foram preenchidos corretamente:");
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Error:" + e);
    }

    }//GEN-LAST:event_jButton1SalvarActionPerformed

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed
        boolean sucesso;
         
        ClienteController clienteController = new ClienteController();
        try{
            sucesso = clienteController.apagarCliente(this.codCliente);
            if(sucesso){
                JOptionPane.showMessageDialog(null, "Cliente apagado!");
                this.jButtonLimparActionPerformed(evt);
            }else{
                JOptionPane.showMessageDialog(null, "Error ao apagar Cliente, por favor selecione novamente.");
            }
        } catch (ExceptionDAO ex) {
            Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }         
    }//GEN-LAST:event_jButtonApagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Salvar;
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JLabel jLabelCadastroCliente;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelNascimento;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JTextField jTextFieldCampoCpf;
    private javax.swing.JTextField jTextFieldCampoEmail;
    private javax.swing.JTextField jTextFieldCampoEndereco;
    private javax.swing.JTextField jTextFieldCampoNascimento;
    private javax.swing.JTextField jTextFieldCampoNome;
    // End of variables declaration//GEN-END:variables

   public void buscarCliente(Integer codAutor, String nome, String cpf, String email, String endereco, Date nascimento) {
            this.codCliente = codCliente;
            this.jTextFieldCampoNome.setText(nome);
            this.jTextFieldCampoCpf.setText(cpf);
            this.jTextFieldCampoEmail.setText(email);
            this.jTextFieldCampoEndereco.setText(endereco);
          SimpleDateFormat mask = new SimpleDateFormat("dd/mm/yyyy");
          this.jTextFieldCampoNascimento.setText(mask.format(nascimento));
    }
}
