/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mycompany.projetopoo.view;

import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import mycompany.projetopoo.controller.LivroController;

/**
 *
 * @author debor
 */
public class TelaCadastroLivros extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroLivros
     */
    public TelaCadastroLivros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCadastroLivro = new javax.swing.JLabel();
        jPanelTelaCadastro = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldCampoTitulo = new javax.swing.JTextField();
        jLabelGenero = new javax.swing.JLabel();
        jComboBoxCampoGenero = new javax.swing.JComboBox<>();
        jLabelResumo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneCampoResumo = new javax.swing.JTextPane();
        jLabelPaginas = new javax.swing.JLabel();
        jComboBoxCampoPaginas = new javax.swing.JComboBox<>();
        jButtonSalvar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca Leia um Livro");
        setResizable(false);

        jLabelCadastroLivro.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabelCadastroLivro.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCadastroLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mycompany/projetopoo/imagens/book.png"))); // NOI18N
        jLabelCadastroLivro.setText("Cadastro de Livros");
        jLabelCadastroLivro.setName(""); // NOI18N

        jPanelTelaCadastro.setBackground(new java.awt.Color(51, 51, 51));

        jLabelNome.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelNome.setText("NOME:");

        jTextFieldCampoTitulo.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldCampoTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldCampoTitulo.setText("  Titulo do Livro...");
        jTextFieldCampoTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldCampoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCampoTituloActionPerformed(evt);
            }
        });

        jLabelGenero.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelGenero.setText("GÊNERO:");
        jLabelGenero.setToolTipText("");

        jComboBoxCampoGenero.setBackground(new java.awt.Color(0, 0, 0));
        jComboBoxCampoGenero.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxCampoGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o gênero...", "Ação", "Animação", "Aventura", "Cinema de arte", "Chanchada", "Comédia", "Comédia romântica", "Comédia dramática", "Comédia de ação", "Dança", "Documentário", "Docuficção", "Drama", "Espionagem", "Faroeste", "Fantasia científica", "Ficção científica", "Filmes de guerra", "Musical", "Filme policial", "Romance", "Seriado", "Suspense", "Terror" }));
        jComboBoxCampoGenero.setBorder(null);

        jLabelResumo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelResumo.setText("RESUMO:");

        jTextPaneCampoResumo.setBackground(new java.awt.Color(153, 153, 153));
        jTextPaneCampoResumo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextPaneCampoResumo.setForeground(new java.awt.Color(0, 0, 0));
        jTextPaneCampoResumo.setToolTipText("");
        jScrollPane1.setViewportView(jTextPaneCampoResumo);

        jLabelPaginas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelPaginas.setText("PÁGINAS:");

        jComboBoxCampoPaginas.setBackground(new java.awt.Color(0, 0, 0));
        jComboBoxCampoPaginas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o número de páginas...", "15", "20", "30", "40", "50", "60", "70", "80", "90", "100", "200", "300", "400", "500", "600", "700", "800", "900", "1000" }));
        jComboBoxCampoPaginas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCampoPaginasActionPerformed(evt);
            }
        });

        jButtonSalvar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonLimpar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonCancelar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonConsultar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonConsultar.setText("Consultar");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTelaCadastroLayout = new javax.swing.GroupLayout(jPanelTelaCadastro);
        jPanelTelaCadastro.setLayout(jPanelTelaCadastroLayout);
        jPanelTelaCadastroLayout.setHorizontalGroup(
            jPanelTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTelaCadastroLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanelTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelTelaCadastroLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanelTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelGenero)
                            .addComponent(jLabelNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCampoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCampoGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelTelaCadastroLayout.createSequentialGroup()
                            .addComponent(jLabelPaginas)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxCampoPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelTelaCadastroLayout.createSequentialGroup()
                                    .addComponent(jButtonSalvar)
                                    .addGap(45, 45, 45)
                                    .addComponent(jButtonLimpar)
                                    .addGap(44, 44, 44)
                                    .addComponent(jButtonCancelar)
                                    .addGap(42, 42, 42)
                                    .addComponent(jButtonConsultar)))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanelTelaCadastroLayout.createSequentialGroup()
                            .addComponent(jLabelResumo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanelTelaCadastroLayout.setVerticalGroup(
            jPanelTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTelaCadastroLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanelTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCampoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome))
                .addGap(18, 18, 18)
                .addGroup(jPanelTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGenero)
                    .addComponent(jComboBoxCampoGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanelTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelResumo)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCampoPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPaginas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanelTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonConsultar))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCadastroLivro)
                .addGap(221, 221, 221))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTelaCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCadastroLivro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelTelaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jComboBoxCampoPaginasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCampoPaginasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCampoPaginasActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
  
    }//GEN-LAST:event_jButtonSalvarActionPerformed
    
    public void salvarTelaCadastroLivro(java.awt.event.MouseEvent evt){
         int numPaginas = Integer.parseInt(jComboBoxCampoPaginas.getItemAt(0).toString());
        String genero = jComboBoxCampoGenero.getSelectedItem().toString();
        boolean sucesso; 
    
    try{
       LivroController livroController = new LivroController();
       sucesso = livroController.cadastraLivro(genero, genero, genero, numPaginas);
        if(sucesso ==true){
            JOptionPane.showMessageDialog(null, "O livro foi cadastrado!");
        this.limparTelaCadastroLivros(evt); 
        }else{
            JOptionPane.showMessageDialog(null, "Os campos nao foram preenchidos corretamente!");
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "ERROR:" + e);
    }
}
    
    public void fecharJanela(java.awt.event.WindowEvent evt){
        this.dispose();
       // telaPrincipal.setVisible(true);
    }
    
    private void limparTelaCadastroLivros(java.awt.event.MouseEvent evt){
        jTextFieldCampoTitulo.setText("");
        jComboBoxCampoGenero.setSelectedIndex(0);
        jTextPaneCampoResumo.setText("");
        jComboBoxCampoPaginas.setSelectedIndex(0);
        
    }
    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:                                        
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jTextFieldCampoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCampoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCampoTituloActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroLivros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSalvar;
    public javax.swing.JComboBox<String> jComboBoxCampoGenero;
    private javax.swing.JComboBox<String> jComboBoxCampoPaginas;
    private javax.swing.JLabel jLabelCadastroLivro;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPaginas;
    private javax.swing.JLabel jLabelResumo;
    private javax.swing.JPanel jPanelTelaCadastro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCampoTitulo;
    private javax.swing.JTextPane jTextPaneCampoResumo;
    // End of variables declaration//GEN-END:variables

}

