/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mycompany.projetopoo.view;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import mycompany.projetopoo.controller.ClienteController;
/**
 *
 * @author debor
 */
public class TelaCliente extends javax.swing.JFrame {

    /**
     * Creates new form TelaCliente
     */
    public TelaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCadastroCliente = new javax.swing.JLabel();
        jPanelCadastro = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldCampoNome = new javax.swing.JTextField();
        jLabelNascimento = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelEndereço = new javax.swing.JLabel();
        jTextFieldCampoNascimento = new javax.swing.JTextField();
        jTextFieldCampoCpf = new javax.swing.JTextField();
        jTextFieldCampoEmail = new javax.swing.JTextField();
        jTextFieldCampoEndereço = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Biblioteca leia um Livro");
        setResizable(false);

        jLabelCadastroCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabelCadastroCliente.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCadastroCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mycompany/projetopoo/imagens/book.png"))); // NOI18N
        jLabelCadastroCliente.setText("Cadastro de Clientes");
        jLabelCadastroCliente.setToolTipText("");

        jPanelCadastro.setBackground(new java.awt.Color(51, 51, 51));

        jLabelNome.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelNome.setText("NOME:");

        jTextFieldCampoNome.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldCampoNome.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldCampoNome.setText("  Informe o nome do cliente...");
        jTextFieldCampoNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldCampoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCampoNomeActionPerformed(evt);
            }
        });

        jLabelNascimento.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelNascimento.setText("NASCIMENTO:");

        jLabelCpf.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelCpf.setText("CPF:");

        jLabelEmail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelEmail.setText("E-MAIL:");
        jLabelEmail.setToolTipText("");

        jLabelEndereço.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelEndereço.setText("ENDEREÇO:");

        jTextFieldCampoNascimento.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldCampoNascimento.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldCampoNascimento.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldCampoNascimento.setText("    /    / ");
        jTextFieldCampoNascimento.setToolTipText("");
        jTextFieldCampoNascimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldCampoNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCampoNascimentoActionPerformed(evt);
            }
        });

        jTextFieldCampoCpf.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldCampoCpf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldCampoCpf.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldCampoCpf.setText(" xxx.xxx.xxx-xx");
        jTextFieldCampoCpf.setToolTipText("");
        jTextFieldCampoCpf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldCampoCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCampoCpfActionPerformed(evt);
            }
        });

        jTextFieldCampoEmail.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldCampoEmail.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldCampoEmail.setText("  ...seuEmail@gmail.com");
        jTextFieldCampoEmail.setToolTipText("");
        jTextFieldCampoEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextFieldCampoEndereço.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldCampoEndereço.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldCampoEndereço.setText("  Informe o endereço completo do cliente...");
        jTextFieldCampoEndereço.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonSalvar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonSalvar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSalvar.setText("Salvar");

        jButtonLimpar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonLimpar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonLimpar.setText("Limpar");

        jButtonCancelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonConsultar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonConsultar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonConsultar.setText("Consultar");

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabelCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCampoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNome)
                            .addComponent(jLabelNascimento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCampoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelEndereço)
                            .addComponent(jLabelEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                    .addComponent(jButtonSalvar)
                                    .addGap(60, 60, 60)
                                    .addComponent(jButtonLimpar)
                                    .addGap(72, 72, 72)
                                    .addComponent(jButtonCancelar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonConsultar))
                                .addComponent(jTextFieldCampoEndereço, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldCampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNascimento)
                    .addComponent(jTextFieldCampoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCampoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCpf))
                .addGap(16, 16, 16)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEndereço)
                    .addComponent(jTextFieldCampoEndereço, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonConsultar))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabelCadastroCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCadastroCliente)
                .addGap(18, 18, 18)
                .addComponent(jPanelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCampoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCampoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCampoNomeActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed
MaskFormatter mascaraCpf = null;
    private void jTextFieldCampoCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCampoCpfActionPerformed
        try {
            // TODO add your handling code here:
            mascaraCpf = new MaskFormatter("###.###.###-##");
        } catch (ParseException ex) {
            Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextFieldCampoCpfActionPerformed
MaskFormatter mascaraData = null;
    private void jTextFieldCampoNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCampoNascimentoActionPerformed
        try {
            // TODO add your handling code here:
            mascaraData = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextFieldCampoNascimentoActionPerformed
    private void fecharJanela(java.awt.event.WindowEvent evt){
        // telaPrincipal.setVisible(true);    
    }
    
    
    private void salvarCliente(java.awt.event.MouseEvent evt){
    boolean sucesso;
    
    try{
        ClienteController clienteController = new ClienteController();
        sucesso = clienteController.cadastrarCliente(jTextFieldCampoNome.getText(), jTextFieldCampoCpf.getText(), jTextFieldCampoEmail.getText(),
                jTextFieldCampoEndereço.getText(), jTextFieldCampoNascimento.getText());
        if(sucesso == true){
            JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso!");
            this.limparTelaCadastroCliente(evt);
        }else{
            JOptionPane.showMessageDialog(null, "Verifique os campos que nao foram preenchidos corretamente:");
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Error:" + e);
    }
}
    private void limparTelaCadastroCliente(java.awt.event.MouseEvent evt){
        jTextFieldCampoNome.setText("");
        jTextFieldCampoCpf.setText("");
        jTextFieldCampoEmail.setText("");
        jTextFieldCampoEndereço.setText("");
        jTextFieldCampoNascimento.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelCadastroCliente;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEndereço;
    private javax.swing.JLabel jLabelNascimento;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JTextField jTextFieldCampoCpf;
    private javax.swing.JTextField jTextFieldCampoEmail;
    private javax.swing.JTextField jTextFieldCampoEndereço;
    private javax.swing.JTextField jTextFieldCampoNascimento;
    private javax.swing.JTextField jTextFieldCampoNome;
    // End of variables declaration//GEN-END:variables
}
